name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Deploy to EC2
    runs-on: macOS-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o ./build .
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: build/
          TARGET: ${{ secrets.TARGET_DIR }}