name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: macos-latest
    env:
      SERVICE_NAME: todolist
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Create output directory
        run: mkdir -p ./build

      - name: Build
        run: go build -v -o ./build/$SERVICE_NAME

  deploy:
    name: Deploy to EC2
    runs-on: macos-latest
    needs: build
    env:
      SERVICE_NAME: ${{ env.SERVICE_NAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      HOST_DNS: ${{ secrets.HOST_DNS }}
      USERNAME: ${{ secrets.USERNAME }}
      TARGET_DIR: ${{ secrets.TARGET_DIR }}
    steps:
      - name: Generate .env file
        run: ./generate_env.sh

      - name: Deploy to EC2
        run: |
          echo "$SSH_PRIVATE_KEY" | tr-d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST sudo systemctl stop $SERVICE_NAME
          scp -o StrictHostKeyChecking=no -r build $REMOTE_USER@$REMOTE_HOST:TARGET_DIR
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST chmod +x $TARGET/$SERVICE_NAME
